import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import isAuth from "../../components/RequireAuth";
// import './globals.css';
import ReactQueryProvider from "./providers/ReactQueryProvider";
import Link from "next/link";
import { useAuthState } from "react-firebase-hooks/auth";
import auth from "../../firebase.init";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div>{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}